env:
  matrix:
    - TZ=Europe/London
    - TZ=America/Los_Angeles

os:
  - linux
  - osx

language: r
sudo: false
cache: packages

addons:
  apt:
    update: TRUE

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm &&
    export PATH="/usr/local/opt/llvm/bin:$PATH" &&
    export LDFLAGS="-L/usr/local/opt/llvm/lib" &&
    export CFLAGS="-I/usr/local/opt/llvm/include"; fi
  - pip install --upgrade pip
  - pip install numpy

r_packages:
  - covr
  - rmarkdown

after_success:
  - Rscript -e 'covr::codecov()'
